UNKNOWN_ACTION:
  severity: MEDIUM

RESOURCE_STAR:
  ignore_locations:
    - Action:
        - "s3:PutObject"
        - "s4.*"
RESOURCE_MISMATCH:
  ignore_locations:
  - Action:
    - ".*s3.*"

  - filepath: "dex.json"
    Action: "s3:GetObject"
    # resource:
    #   - "a"
